A
hilti: uncaught exception, myException2 with argument hallo (from /Users/robin/work/binpacpp/hilti2/tests/.tmp/exceptions.throw-3/throw.hlt:14-14)
