hilti: uncaught exception, InternalError with argument 'My personal internal error.' (from /da/home/robin/work/binpacpp/hilti2/tests/.tmp/debug.internal-error/internal-error.hlt:11-12)
