hilti: uncaught exception, InternalError with argument 'My personal internal error.' (from /home/robin/work/hilti/tests/.tmp/hilti.debug.internal-error/internal-error.hlt:11-12)
