A
hilti: uncaught exception, myException with argument 'hallo' (from /home/robin/work/hilti/tests/.tmp/hilti.exceptions.throw-2/throw.hlt:13-14)
