module Main

import Hilti

type myException = exception
void run()
{

  local ref<myException> e
  local ref<myException> e_2
  
  
      # pred: { <none> } succ: { [0059] }
      # def: { <none> } clear: { <none> } mod: { <none> } read: { <none> }
      # live-in: { <none> } live-out: { <none> }
      # now-dead: { <none> }
      [0058] call Hilti::print ("A")
      # pred: { [0058] } succ: { [0060] }
      # def: { <none> } clear: { <none> } mod: { <none> } read: { <none> }
      # live-in: { <none> } live-out: { <none> }
      # now-dead: { <none> }
      [0059] exception.__begin_handler @__catch_1 Main::myException
      # pred: { [0059] } succ: { [0061], [0066] }
      # def: { run%e.2 } clear: { <none> } mod: { <none> } read: { <none> }
      # live-in: { <none> } live-out: { run%e.2 }
      # now-dead: { <none> }
      [0060] e = new Main::myException
      # pred: { [0060] } succ: { [0062], [0066] }
      # def: { <none> } clear: { <none> } mod: { run%e.2 } read: { <none> }
      # live-in: { run%e.2 } live-out: { <none> }
      # now-dead: { run%e.2 }
      [0061] exception.throw e
      # pred: { [0061] } succ: { [0063], [0066] }
      # def: { <none> } clear: { <none> } mod: { <none> } read: { <none> }
      # live-in: { <none> } live-out: { <none> }
      # now-dead: { <none> }
      [0062] call Hilti::print ("Cannot be reached")
      # pred: { [0062] } succ: { [0064], [0066] }
      # def: { <none> } clear: { <none> } mod: { <none> } read: { <none> }
      # live-in: { <none> } live-out: { <none> }
      # now-dead: { <none> }
      [0063] exception.__end_handler
      # pred: { [0063] } succ: { [0071] }
      # def: { <none> } clear: { <none> } mod: { <none> } read: { <none> }
      # live-in: { <none> } live-out: { <none> }
      # now-dead: { <none> }
      [0064] jump @__catch_cont_1
  
  @__catch_1:
      # pred: { [0060], [0061], [0062], [0063] } succ: { [0067] }
      # def: { run%e_2.2 } clear: { <none> } mod: { <none> } read: { <none> }
      # live-in: { <none> } live-out: { <none> }
      # now-dead: { run%e.2, run%e_2.2 }
      [0066] e_2 = exception.__get_and_clear
      # pred: { [0066] } succ: { [0068] }
      # def: { <none> } clear: { <none> } mod: { <none> } read: { <none> }
      # live-in: { <none> } live-out: { <none> }
      # now-dead: { <none> }
      [0067] call Hilti::print ("Caught it!")
      # pred: { [0067] } succ: { [0071] }
      # def: { <none> } clear: { <none> } mod: { <none> } read: { <none> }
      # live-in: { <none> } live-out: { <none> }
      # now-dead: { <none> }
      [0068] jump @__catch_cont_1
  
  @__catch_cont_1:
      # pred: { [0064], [0068] } succ: { [0072] }
      # def: { <none> } clear: { <none> } mod: { <none> } read: { <none> }
      # live-in: { <none> } live-out: { <none> }
      # now-dead: { <none> }
      [0071] call Hilti::print ("C")
      # pred: { [0071] } succ: { <none> }
      # def: { <none> } clear: { <none> } mod: { <none> } read: { <none> }
      # live-in: { <none> } live-out: { <none> }
      # now-dead: { <none> }
      [0072] return.void
  
}



  # pred: { <none> } succ: { <none> }
  # def: { <none> } clear: { <none> } mod: { <none> } read: { <none> }
  # live-in: { <none> } live-out: { <none> }
  # now-dead: { <none> }
  [0075] block.end

