RUN 1
hilti: uncaught exception in worker thread, DivisionByZero (from /da/home/robin/work/binpacpp/hilti2/tests/.tmp/threads.exceptions-2/exceptions.hlt:12-14)
hilti: uncaught exception, ThreadException (from /home/robin/work/binpacpp/hilti2/libhilti/threading.c:548)
RUN 2
hilti: uncaught exception in worker thread, DivisionByZero (from /da/home/robin/work/binpacpp/hilti2/tests/.tmp/threads.exceptions-2/exceptions.hlt:12-14)
hilti: uncaught exception, ThreadException (from /home/robin/work/binpacpp/hilti2/libhilti/threading.c:548)
RUN 3
hilti: uncaught exception in worker thread, DivisionByZero (from /da/home/robin/work/binpacpp/hilti2/tests/.tmp/threads.exceptions-2/exceptions.hlt:12-14)
hilti: uncaught exception, ThreadException (from /home/robin/work/binpacpp/hilti2/libhilti/threading.c:548)
RUN 4
hilti: uncaught exception in worker thread, DivisionByZero (from /da/home/robin/work/binpacpp/hilti2/tests/.tmp/threads.exceptions-2/exceptions.hlt:12-14)
hilti: uncaught exception, ThreadException (from /home/robin/work/binpacpp/hilti2/libhilti/threading.c:548)
RUN 5
hilti: uncaught exception in worker thread, DivisionByZero (from /da/home/robin/work/binpacpp/hilti2/tests/.tmp/threads.exceptions-2/exceptions.hlt:12-14)
hilti: uncaught exception, ThreadException (from /home/robin/work/binpacpp/hilti2/libhilti/threading.c:548)
