RUN 1
hilti: uncaught exception in worker thread, DivisionByZero (from /home/robin/work/hilti/tests/.tmp/hilti.threads.exceptions-2/exceptions.hlt:12-14)
hilti: uncaught exception, ThreadException (from /home/robin/work/hilti/libhilti/threading.c:654)
RUN 2
hilti: uncaught exception in worker thread, DivisionByZero (from /home/robin/work/hilti/tests/.tmp/hilti.threads.exceptions-2/exceptions.hlt:12-14)
hilti: uncaught exception, ThreadException (from /home/robin/work/hilti/libhilti/threading.c:654)
RUN 3
hilti: uncaught exception in worker thread, DivisionByZero (from /home/robin/work/hilti/tests/.tmp/hilti.threads.exceptions-2/exceptions.hlt:12-14)
hilti: uncaught exception, ThreadException (from /home/robin/work/hilti/libhilti/threading.c:654)
RUN 4
hilti: uncaught exception in worker thread, DivisionByZero (from /home/robin/work/hilti/tests/.tmp/hilti.threads.exceptions-2/exceptions.hlt:12-14)
hilti: uncaught exception, ThreadException (from /home/robin/work/hilti/libhilti/threading.c:654)
RUN 5
hilti: uncaught exception in worker thread, DivisionByZero (from /home/robin/work/hilti/tests/.tmp/hilti.threads.exceptions-2/exceptions.hlt:12-14)
hilti: uncaught exception, ThreadException (from /home/robin/work/hilti/libhilti/threading.c:654)
